#!/usr/bin/env python3
import pandas as pd
import argparse
import os

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", required=True, help="Path to global CSV")
    parser.add_argument("--topk", type=int, default=15)
    args = parser.parse_args()

    if not os.path.exists(args.csv):
        print(f"❌ File not found: {args.csv}")
        return

    df = pd.read_csv(args.csv)

    print(f"\n{'='*70}")
    print(f"🌍 PRO-M3E GLOBAL BIOMARKER RANKING")
    print(f"Target: {os.path.basename(args.csv)}")
    print(f"{'='*70}")
    
    # Read the exact columns generated by aggregate_global.py
    for i, row in df.head(args.topk).iterrows():
        name = row.get('ROI_Name', 'Unknown')
        mag = row.get('Global_Saliency_Mean', 0.0)
        z_score = row.get('Robustness_Z_Score', 0.0)
        
        print(f"{i+1:2}. {name:35} | Saliency: {mag} | Robustness (Z): {z_score}")

    print(f"{'='*70}")
    
    if not df.empty:
        top_roi = df.iloc[0].get('ROI_Name', 'Top feature')
        print(f"💡 CLINICAL SUMMARY: '{top_roi}'")
        print(f"   is the most critical and consistent biomarker for this task across your cohort.")

if __name__ == "__main__":
    main()